# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c39302ee40b79503da20ec8b65939a22"
name = "Sennheiser store locator app"
application_url = "https://dechbstorelocatorprd-b2dccxb2bffgf4fa.westeurope-01.azurewebsites.net"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dechbstorelocatorprd-b2dccxb2bffgf4fa.westeurope-01.azurewebsites.net/api/auth/callback"
]